export const FETCH_NEWS = "FETCH_NEWS";
export const REMOVE = "REMOVE";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";

export const ACTIVE_CATEGORY = "ACTIVE_CATEGORY";

export const ADD_COUNTRY = "ADD_COUNTRY";
export const REMOVE_COUNTRY = "REMOVE_COUNTRY";

export const BAN_RESOURCE = "BAN_RESOURCE";
export const UNBAN_RESOURCE = "UNBAN_RESOURCE";

export const SETTINGS_UPDATED = "SETTINGS_UPDATED";
